### ISSUE TITLE
Issue with "No" Button in Dark Theme

### ISSUE THREAD

**Issue by Crybabby** [shinnenkara/valentines-day#1]
I've identified an issue with the "No" button in the dark theme of the application. It consistently extends beyond the boundaries of the background, causing a visual inconsistency.

Expected Behavior:
The "No" button should stay within the confines of the background, maintaining a visually cohesive appearance.
Screenshot:

![photo_2024-02-12_22-47-31](https://github.com/shinnenkara/valentines-day/assets/104210005/0496072a-11ce-4ccb-8503-be534a403811)

**Comment by shinnenkara** [comment]
Thanks for the test and open issue. Should be fixed here: https://github.com/shinnenkara/valentines-day/commit/c0fa539523a36624aab1876e9387bcbebc6539ac
